version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - pip install --upgrade pip
      - pip install -r ./jobPortal/requirements.txt
      - pip install pylint
      - echo "Build started on `date`"
      - echo "Compiling the code"
      - echo `$CODEBUILD_SRC_DIR`
  post_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/jobPortal/manage.py
      - echo `$CODEBUILD_SRC_DIR`
      - pylint $CODEBUILD_SRC_DIR/jobPortal/*.py
artifacts:
  files:
    - '**/*'