# Generated by Django 5.0.3 on 2024-03-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('experience_level', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=5000)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=1000)),
                ('experience', models.IntegerField()),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblistings.jobpost')),
            ],
        ),
    ]
